name: Continuous Lint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: clang-tidy check
        uses: smay1613/clang-tidy-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
